/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xnetp_poc_sockets_RawSocket */

#ifndef _Included_xnetp_poc_sockets_RawSocket
#define _Included_xnetp_poc_sockets_RawSocket
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _AF_INET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1AF_1INET
  (JNIEnv *, jclass);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _AF_INET6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1AF_1INET6
  (JNIEnv *, jclass);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _socket
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1socket
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1close
  (JNIEnv *, jclass, jint);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _setSendBufferSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1setSendBufferSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _setReceiveBufferSize
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1setReceiveBufferSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _receive4
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1receive4
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _receive6
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1receive6
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _send4
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1send4
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _send6
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1send6
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1errno
  (JNIEnv *, jclass);
  

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _sendmmsg4
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1sendmmsg4
  (JNIEnv *, jclass, jint, jobject, jint, jint);


/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _sendmmsg6
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1sendmmsg6
  (JNIEnv *, jclass, jint, jobject, jint, jint);


/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _rectmmsg4
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1recvmmsg4
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     xnetp_poc_sockets_RawSocket
 * Method:    _rectmmsg6
 * Signature: (ILjava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RawSocket__1recvmmsg6
  (JNIEnv *, jclass, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
