/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xnetp_poc_sockets_RxRing */

#ifndef _Included_xnetp_poc_sockets_RxRing
#define _Included_xnetp_poc_sockets_RxRing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xnetp_poc_sockets_RxRing
 * Method:    _socket
 * Signature: (Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RxRing__1socket
  (JNIEnv *, jclass, jint, jobject, jint, jint, jint);

/*
 * Class:     xnetp_poc_sockets_RxRing
 * Method:    _poll
 * Signature: ()Z
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RxRing__1poll
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     xnetp_poc_sockets_RxRing
 * Method:    _close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RxRing__1close
  (JNIEnv *, jclass, jint, jobject, jint, jint);


/*
 * Class:     xnetp_poc_sockets_RxRing
 * Method:    _X_close
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RxRing__1X_1close
  (JNIEnv *, jclass, jint, jobject, jint, jint);

/*
 * Class:     xnetp_poc_sockets_RxRing
 * Method:    _errno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_sockets_RxRing__1errno
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
