/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xnetp_poc_affinity_Affinity */

#ifndef _Included_xnetp_poc_affinity_Affinity
#define _Included_xnetp_poc_affinity_Affinity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xnetp_poc_affinity_Affinity
 * Method:    __getAffinity
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_xnetp_poc_affinity_Affinity__1_1getAffinity
  (JNIEnv *, jclass);

/*
 * Class:     xnetp_poc_affinity_Affinity
 * Method:    __setAffinity
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_xnetp_poc_affinity_Affinity__1_1setAffinity
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     xnetp_poc_affinity_Affinity
 * Method:    __getThreadId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xnetp_poc_affinity_Affinity__1_1getThreadId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
